name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            APP_DIR="/home/ubuntu/myapp"

            if [ ! -d "$APP_DIR" ]; then
              git clone ${{ secrets.REPO_URL }} "$APP_DIR"
            else
              if [ ! -d "$APP_DIR/.git" ]; then
                rm -rf "$APP_DIR"
                git clone ${{ secrets.REPO_URL }} "$APP_DIR"
              fi
            fi

            cd "$APP_DIR"
            git reset --hard
            git pull origin master

            npm install --omit=dev --no-audit --no-fund

            pm2 restart myapp || pm2 start index.js --name myapp
