name: Deploy to EC2

on:
  push:
    branches:
      - master  # Trigger deployment on master branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Go to app folder or clone if missing
            if [ ! -d "/home/ubuntu/myapp/.git" ]; then
              git clone ${{ secrets.REPO_URL }} /home/ubuntu/myapp
            fi
            cd /home/ubuntu/myapp

            # Pull latest code
            git pull

            # Install dependencies
            npm install --production

            # Start or restart with PM2
            pm2 restart myapp || pm2 start app.js --name myapp
